// <auto-generated />
using System;
using ConestogaVirtualGameStore.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConestogaVirtualGameStore.Migrations
{
    [DbContext(typeof(VirtualGameStoreContext))]
    [Migration("20241110220334_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Address = "108 University Ave E",
                            City = "Waterloo",
                            Country = "Canada",
                            Date = new DateTime(2024, 12, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "A meetup event with the Conestoga Esports team and their fans",
                            Name = "Conestoga Esports Meetup",
                            PostalCode = "N2J 2W2",
                            Province = "Ontario"
                        },
                        new
                        {
                            EventId = 2,
                            Address = "299 Doon Valley Dr",
                            City = "Kitchener",
                            Country = "Canada",
                            Date = new DateTime(2024, 12, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A retro game sale with many popular and beloved classic games",
                            Name = "Conestoga Retro Game Sale",
                            PostalCode = "N2G 4M4",
                            Province = "Ontario"
                        },
                        new
                        {
                            EventId = 3,
                            Address = "775 Main Street East",
                            City = "Milton",
                            Country = "Canada",
                            Date = new DateTime(2024, 12, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A game convention with sales, fan-favourite game actors, and sneak peak on new game releases on the Conestoga Video Game Store website",
                            Name = "Conestoga Gaming Convention",
                            PostalCode = "L9T 3Z3",
                            Province = "Ontario"
                        },
                        new
                        {
                            EventId = 4,
                            Address = "850 Fountain Street South",
                            City = "Cambridge",
                            Country = "Canada",
                            Date = new DateTime(2024, 12, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A game tournament that has competitors facing each other in various fighting and fps games to win a cash prize",
                            Name = "Conestoga Gaming Tournament",
                            PostalCode = "N3H 0A8",
                            Province = "Ontario"
                        });
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("CoverImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202208/1718/NFf86jgU4AeVYgJBEoEKBpxW.jpg",
                            Description = "An action RPG set in a historical setting, featuring stealth and combat elements.",
                            Genere = "Action RPG",
                            Platform = "PlayStation 5, Xbox Series X/S, PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Assassin's Creed Mirage"
                        },
                        new
                        {
                            GameId = 2,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202308/1722/15f4ab1e0fe6a37609b164362a653c0e5bcee98a861d0f10.png",
                            Description = "The latest installment in the Call of Duty series, offering intense first-person shooter action.",
                            Genere = "First-Person Shooter",
                            Platform = "PlayStation 5, Xbox Series X/S, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Call of Duty MW3"
                        },
                        new
                        {
                            GameId = 3,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202008/0416/6Bo40lnWU0BhgrOUm7Cb6by3.png",
                            Description = "A futuristic open-world RPG set in the dystopian Night City, filled with cybernetic enhancements and complex narratives.",
                            Genere = "Action RPG",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 39.99m,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            GameId = 4,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
                            Description = "An epic sequel to the critically acclaimed God of War, featuring Norse mythology and Kratos' journey.",
                            Genere = "Action-Adventure",
                            Platform = "PlayStation 4, PlayStation 5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War Ragnarok"
                        },
                        new
                        {
                            GameId = 5,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202207/2509/85p2Dwh5iDhUzRKe40QeNYh3.png",
                            Description = "A modern remake of the classic survival horror game, offering updated graphics and gameplay mechanics.",
                            Genere = "Survival Horror",
                            Platform = "PlayStation 4, PlayStation 5, Xbox Series X/S, PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil 4 Remake"
                        },
                        new
                        {
                            GameId = 6,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202312/0117/315718bce7eed62e3cf3fb02d61b81ff1782d6b6cf850fa4.png",
                            Description = "A narrative-driven action-adventure game that continues the story of Ellie and Joel in a post-apocalyptic world.",
                            Genere = "Action-Adventure",
                            Platform = "PlayStation 4",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Last of Us: Part 2"
                        },
                        new
                        {
                            GameId = 7,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/phvVT0qZfcRms5qDAk0SI3CM.png",
                            Description = "In a dark fantasy world created by Hidetaka Miyazaki (Dark Souls) and George R. R. Martin (A Song of Ice and Fire), the player is a Tarnished who is called back to the Lands Between to restore the Elden Ring and become the Elden Lord.",
                            Genere = "Action RPG",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            GameId = 8,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202205/2800/W5uSEsW7yefCNTHatS03v5q7.png",
                            Description = "Task Force 141 faces its greatest threat yet - a newly aligned menace with deep, yet unknown, connections.",
                            Genere = "First-Person Shooter",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2022, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Call of Duty: Modern Warfare II"
                        },
                        new
                        {
                            GameId = 9,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202009/2419/BWMVfyxONkIAlAJVQd96qPuN.png",
                            Description = "In the post-apocalyptic Boston, Massachusetts area, you play as the Sole Survivor of Vault 111, recently revived from centuries of forced cryostasis, determined to find your kidnapped son.",
                            Genere = "Action RPG",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2015, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fallout 4"
                        },
                        new
                        {
                            GameId = 10,
                            CoverImageURL = "https://image.api.playstation.com/cdn/UP0002/CUSA08829_00/xmKUnAOenEAKspB3FlOg80aQZfEoCYcE.png",
                            Description = "Captain Price and the SAS partner with the CIA and the Urzikstani Liberation Force to retrieve stolen chemical weapons. The fight takes you from London to the Middle East and beyond, as this joint task force battles to stop a global war.",
                            Genere = "First-Person Shooter",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 59.99m,
                            ReleaseDate = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Call of Duty: Modern Warfare"
                        },
                        new
                        {
                            GameId = 11,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/1c7b75d8ed9271516546560d219ad0b22ee0a263b4537bd8.png",
                            Description = "Spider-Men, Peter Parker and Miles Morales, return for an exciting new adventure in the critically acclaimed Marvel's Spider-Man franchise.",
                            Genere = "Action-Adventure",
                            Platform = "PlayStation 5",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man 2"
                        },
                        new
                        {
                            GameId = 12,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202405/2921/2819b5df32c19b4b9e972dc3281b474937bb2570312b38a2.png",
                            Description = "As the Gulf War seizes the world's attention, a covert and enigmatic group has penetrated the upper echelons of the CIA, labeling those who oppose them as betrayers. Black Ops veteran Frank Woods and his squad, once celebrated as heroes by their agency and nation, now find themselves banished and pursued by the very military entity that forged them. They are now outcasts in their own land, hunted by the machinery of war that they once served.",
                            Genere = "First-Person Shooter",
                            Platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Call of Duty: Black Ops 6"
                        },
                        new
                        {
                            GameId = 13,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202401/2910/d48262b72a5a2daa3ca3aed6c8f42c44f3fdaf2902265a13.png",
                            Description = "Until Dawn is a branching narrative survival horror game in which any choice of action by the player may cause other consequences later in the story. It was rebuilt from the ground up with stunning visuals in Unreal Engine 5.",
                            Genere = "Survival Horror",
                            Platform = "PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Until Dawn"
                        },
                        new
                        {
                            GameId = 14,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202210/2000/IgwsFz9BiBrFvyV7pIWpoVgd.png",
                            Description = "Having received a letter from his deceased wife, James heads to where they shared so many memories, in the hope of seeing her one more time: Silent Hill. There, by the lake, he finds a woman eerily similar to her.",
                            Genere = "Survival Horror",
                            Platform = "PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silent Hill 2 Remake"
                        },
                        new
                        {
                            GameId = 15,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/img/rnd/202010/2217/p3pYq0QxntZQREXRVdAzmn1w.png",
                            Description = "After wiping out the gods of Mount Olympus, Kratos moves on to the frigid lands of Scandinavia, where he and his son must embark on an odyssey across a dangerous world of gods and monsters.",
                            Genere = "Action-Adventure",
                            Platform = "PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War"
                        },
                        new
                        {
                            GameId = 16,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202305/2420/83ef93949d474052cc87b86617a5498505d4b50390280394.jpg",
                            Description = "13 years after bestselling writer Alan Wake went missing, a string of ritualistic murders occur in the town of Bright Falls, Washington. Saga Anderson, an FBI agent, is sent to Bright Falls to investigate the murders.",
                            Genere = "Survival Horror",
                            Platform = "Xbox Series X/S, PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Alan Wake II"
                        },
                        new
                        {
                            GameId = 17,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202405/3123/1abfc0f37be11993bd5e67fcb1a9e2c0d656142ace2f232e.png",
                            Description = "After millions have been slaughtered by the actions of the High Heavens and Burning Hells alike. In the power vacuum, a legendary name resurfaces - Lilith, daughter of Mephisto, the whispered progenitor of humanity.",
                            Genere = "Action RPG",
                            Platform = "Xbox Series X/S, PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2023, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Diablo IV"
                        },
                        new
                        {
                            GameId = 18,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202209/2121/UlfMBx2yUHge8Vlz7eszqw13.png",
                            Description = "A team of soldiers and militarists are recruited into an elite counter terrorism unit. Their objective is to fight terrorism across the globe. A threat has emerged that targets the Western world and its interests around the world.",
                            Genere = "First-Person Shooter",
                            Platform = "Xbox Series X/S, PlayStation 5, PC",
                            Price = 50.00m,
                            ReleaseDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rainbow Six: Siege"
                        },
                        new
                        {
                            GameId = 19,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/img/cfn/113078vQ_SpN-Wt1Ejgw5dPLXKnMvMfvZuekrerzhAOXaNrwZuCL6R6YEP4lUSGhMDthl6iyr4LbA_w565pBSa1xbUcHXtH8.png",
                            Description = "You are Jesse Faden, a young woman with a troubled past. You become the new Director of the Bureau of Control - Our frontline in researching and fighting against supernatural enemies like the Hiss threatening our very existence.",
                            Genere = "Action-Adventure",
                            Platform = "Xbox Series X/S, PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Control"
                        },
                        new
                        {
                            GameId = 20,
                            CoverImageURL = "https://image.api.playstation.com/vulcan/ap/rnd/202101/0812/FkzwjnJknkrFlozkTdeQBMub.png",
                            Description = "Ethan Winters' world suddenly comes crashing down when Chris Redfield's appearance sets off a chain of events that ultimately leads him to a mysterious village.",
                            Genere = "Survival Horror",
                            Platform = "Xbox Series X/S, PlayStation 5, PC",
                            Price = 69.99m,
                            ReleaseDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil Village"
                        });
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Member", b =>
                {
                    b.Property<int>("Member_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Member_ID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Cart_ID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Language_ID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone_Number")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Postal_Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Province")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Register_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Member_ID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Member_ID = 1,
                            Address = "123 Main St",
                            City = "New York",
                            Country = "USA",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password123",
                            Phone_Number = "555-1234",
                            Postal_Code = "10001",
                            Province = "NY",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7708)
                        },
                        new
                        {
                            Member_ID = 2,
                            Address = "456 Elm St",
                            City = "Toronto",
                            Country = "Canada",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "password456",
                            Phone_Number = "555-5678",
                            Postal_Code = "M5H 2N2",
                            Province = "ON",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7748)
                        },
                        new
                        {
                            Member_ID = 3,
                            Address = "123 Maple St",
                            City = "New York",
                            Country = "USA",
                            Email = "amelia.hawke@example.com",
                            FirstName = "Amelia",
                            LastName = "Hawke",
                            Password = "password123",
                            Phone_Number = "555-1234",
                            Postal_Code = "10001",
                            Province = "NY",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7751)
                        },
                        new
                        {
                            Member_ID = 4,
                            Address = "456 Oak St",
                            City = "Vancouver",
                            Country = "Canada",
                            Email = "leo.montgomery@example.com",
                            FirstName = "Leo",
                            LastName = "Montgomery",
                            Password = "password234",
                            Phone_Number = "555-2345",
                            Postal_Code = "V6B 3A2",
                            Province = "BC",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7753)
                        },
                        new
                        {
                            Member_ID = 5,
                            Address = "789 Pine St",
                            City = "London",
                            Country = "UK",
                            Email = "clara.fitzgerald@example.com",
                            FirstName = "Clara",
                            LastName = "Fitzgerald",
                            Password = "password345",
                            Phone_Number = "555-3456",
                            Postal_Code = "EC1A 1BB",
                            Province = "England",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7756)
                        },
                        new
                        {
                            Member_ID = 6,
                            Address = "101 Birch St",
                            City = "Los Angeles",
                            Country = "USA",
                            Email = "ethan.rivers@example.com",
                            FirstName = "Ethan",
                            LastName = "Rivers",
                            Password = "password456",
                            Phone_Number = "555-4567",
                            Postal_Code = "90001",
                            Province = "CA",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7758)
                        },
                        new
                        {
                            Member_ID = 7,
                            Address = "202 Cedar St",
                            City = "Sydney",
                            Country = "Australia",
                            Email = "sofia.langford@example.com",
                            FirstName = "Sofia",
                            LastName = "Langford",
                            Password = "password567",
                            Phone_Number = "555-5678",
                            Postal_Code = "2000",
                            Province = "NSW",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7760)
                        },
                        new
                        {
                            Member_ID = 8,
                            Address = "303 Willow St",
                            City = "Chicago",
                            Country = "USA",
                            Email = "jackson.mercer@example.com",
                            FirstName = "Jackson",
                            LastName = "Mercer",
                            Password = "password678",
                            Phone_Number = "555-6789",
                            Postal_Code = "60601",
                            Province = "IL",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7763)
                        },
                        new
                        {
                            Member_ID = 9,
                            Address = "404 Elm St",
                            City = "Montreal",
                            Country = "Canada",
                            Email = "ava.kensington@example.com",
                            FirstName = "Ava",
                            LastName = "Kensington",
                            Password = "password789",
                            Phone_Number = "555-7890",
                            Postal_Code = "H3B 2A7",
                            Province = "QC",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7766)
                        },
                        new
                        {
                            Member_ID = 10,
                            Address = "505 Pine St",
                            City = "Manchester",
                            Country = "UK",
                            Email = "oliver.stanton@example.com",
                            FirstName = "Oliver",
                            LastName = "Stanton",
                            Password = "password890",
                            Phone_Number = "555-8901",
                            Postal_Code = "M1 1AE",
                            Province = "England",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7768)
                        },
                        new
                        {
                            Member_ID = 11,
                            Address = "606 Oak St",
                            City = "Melbourne",
                            Country = "Australia",
                            Email = "isabella.drake@example.com",
                            FirstName = "Isabella",
                            LastName = "Drake",
                            Password = "password901",
                            Phone_Number = "555-9012",
                            Postal_Code = "3000",
                            Province = "VIC",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7770)
                        },
                        new
                        {
                            Member_ID = 12,
                            Address = "707 Maple St",
                            City = "San Francisco",
                            Country = "USA",
                            Email = "mason.carlisle@example.com",
                            FirstName = "Mason",
                            LastName = "Carlisle",
                            Password = "password012",
                            Phone_Number = "555-0123",
                            Postal_Code = "94101",
                            Province = "CA",
                            Register_Date = new DateTime(2024, 11, 10, 17, 3, 34, 21, DateTimeKind.Local).AddTicks(7773)
                        });
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.MemberEvent", b =>
                {
                    b.Property<int>("MemberEvent_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberEvent_ID"));

                    b.Property<int>("Event_ID")
                        .HasColumnType("int");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.HasKey("MemberEvent_ID");

                    b.ToTable("MembersEvents");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.MemberRelationship", b =>
                {
                    b.Property<int>("MemberRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberRelationshipId"));

                    b.Property<int>("MemberAdded_ID")
                        .HasColumnType("int");

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<int>("Relationship_ID")
                        .HasColumnType("int");

                    b.HasKey("MemberRelationshipId");

                    b.HasIndex("MemberAdded_ID");

                    b.HasIndex("Member_ID");

                    b.HasIndex("Relationship_ID");

                    b.ToTable("MembersRelationships");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Relationship", b =>
                {
                    b.Property<int>("Relationship_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Relationship_ID"));

                    b.Property<string>("Relationship_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Relationship_ID");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            Relationship_ID = 1,
                            Relationship_Type = "Friend"
                        },
                        new
                        {
                            Relationship_ID = 2,
                            Relationship_Type = "Family"
                        });
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Wishlist", b =>
                {
                    b.Property<int>("Wishlist_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Wishlist_ID"));

                    b.Property<int>("Member_ID")
                        .HasColumnType("int");

                    b.Property<string>("Wishlist_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Wishlist_ID");

                    b.HasIndex("Member_ID");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Wishlist_Games", b =>
                {
                    b.Property<int>("Wishlist_ID")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Wishlist_ID", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Wishlist_Games");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.MemberRelationship", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.Member", "MemberAdded")
                        .WithMany("MemberRelationshipRelated")
                        .HasForeignKey("MemberAdded_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConestogaVirtualGameStore.Models.Member", "Member")
                        .WithMany("MemberRelationshipPrimary")
                        .HasForeignKey("Member_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConestogaVirtualGameStore.Models.Relationship", "Relationship")
                        .WithMany("MemberRelationship")
                        .HasForeignKey("Relationship_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MemberAdded");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Wishlist", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.Member", "Member")
                        .WithMany("Wishlists")
                        .HasForeignKey("Member_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Wishlist_Games", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.Game", "Game")
                        .WithMany("Wishlist_Games")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConestogaVirtualGameStore.Models.Wishlist", "Wishlist")
                        .WithMany("Wishlist_Games")
                        .HasForeignKey("Wishlist_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConestogaVirtualGameStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConestogaVirtualGameStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Game", b =>
                {
                    b.Navigation("Wishlist_Games");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Member", b =>
                {
                    b.Navigation("MemberRelationshipPrimary");

                    b.Navigation("MemberRelationshipRelated");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Relationship", b =>
                {
                    b.Navigation("MemberRelationship");
                });

            modelBuilder.Entity("ConestogaVirtualGameStore.Models.Wishlist", b =>
                {
                    b.Navigation("Wishlist_Games");
                });
#pragma warning restore 612, 618
        }
    }
}
